from django.conf import settings

BLOCKCHAIN_API_KEY = getattr(settings, 'BLOCKCHAIN_API_KEY', None)
BLOCKCHAIN_DESTINATION_ADDRESS = getattr(settings, 'BLOCKCHAIN_DESTINATION_ADDRESS', None)
BLOCKCHAIN_RECEIVE_API_ENDPOINT = getattr(settings, 'BLOCKCHAIN_RECEIVE_API_ENDPOINT', None)
BLOCKCHAIN_RECEIVE_NOTIFICATION_MODEL = getattr(settings, 'BLOCKCHAIN_RECEIVE_NOTIFICATION_MODEL', None)
BLOCKCHAIN_RECEIVE_CONFIRMATION_LIMIT = getattr(settings, 'BLOCKCHAIN_RECEIVE_CONFIRMATION_LIMIT', None)

